name: "游냍 Reporte de Error"
description: Crear un nuevo ticket para un error. Por favor, a침ade una label de "severity/XXXX" de las disponibles en funci칩n de la gravedad del error.
title: "[BUG] - <t칤tulo>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: descripcion
    attributes:
      label: "Descripci칩n"
      description: Por favor, introduce una descripci칩n expl칤cita de tu problema
      placeholder: Descripci칩n breve y expl칤cita de tu incidente...
    validations:
      required: true
  - type: textarea
    id: pasos-reproduccion
    attributes:
      label: "Pasos para Reproducci칩n"
      description: Por favor, introduce una descripci칩n expl칤cita de tu problema
      value: |
        1. Ir a '...'
        2. Hacer clic en '....'
        3. Desplazarse hacia abajo hasta '....'
        4. Ver el error
      render: bash
    validations:
      required: true
  - type: textarea
    id: capturas
    attributes:
      label: "Capturas de Pantalla"
      description: Si es aplicable, a침ade capturas de pantalla para ayudar a explicar tu problema.
      value: |
        ![DESCRIPCI칍N](ENLACE.png)
      render: bash
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Por favor, copia y pega cualquier salida de logs relevante. Esto se formatear치 autom치ticamente como c칩digo, por lo que no es necesario a침adir comillas inversas.
      render: bash
    validations:
      required: false
  - type: dropdown
    id: navegadores
    attributes:
      label: "Navegadores"
      description: 쮼n qu칠 navegadores ves el problema?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
    validations:
      required: false
